#!/usr/bin/env bash

# Wrap tools for easy use.
_CP_=$(which cp)
_CUT_=$(which cut)
_DIRNAME_=$(which dirname)
_ECHO_=$(which echo)
_JQ_=$(which jq)
_MKDIR_=$(which mkdir)
_REALPATH_=$(which realpath)
_PRINTF_=$(which printf)
_PWD_=$(which pwd)
_SHA_=$(which sha256sum)
_TOUCH_=$(which touch)

# Absolute path; parameters: current value, default value
_get_abspath_() { $_ECHO_ "${1:+$($_REALPATH_ -m $1)}${1:-$($_REALPATH_ -m $2)}"; }

# Default configuration file (can be overriden)
: ${HOME:="~"}
XDG_CONFIG_HOME=$(_get_abspath_ "$XDG_CONFIG_HOME" "$HOME/.config")
CLODBOX_CONFIG_FILE="$XDG_CONFIG_HOME/clodbox/clodbox.rc"

# Primary / main function; starts clodbox container.
_clodbox_start_() {
  # Fetch or construct all necessary paths.
  _clodbox_load_std_paths_
  _clodbox_fetch_project_paths_

  ENTRYPT=${1:+"--entrypoint \"$1\""}
  OAUTH_TOKEN=$($_JQ_ -r '.claudeAiOauth.accessToken' $PROJECT_DOT_PATH/.credentials.json)

  # Execute podman or docker.
  docker run -it --rm --userns=keep-id \
    -v "$PROJECT_PATH":/home/agent/workspace:Z,U \
    -w /home/agent/workspace \
    -v "$PROJECT_DOT_PATH":/home/agent/.claude:Z,U \
    -v "$PROJECT_CFG_FILE":/home/agent/.claude.json:Z,U \
    -e "CLAUDE_CODE_OAUTH_TOKEN=$OAUTH_TOKEN" "$ENTRYPT" \
    "$CLODBOX_CONTAINER_IMAGE"
}

# Process standardized directories.
_clodbox_load_std_paths_() {
  # Fetch / normalize XDG variables (or get their defaults)
  XDG_DATA_HOME=$(_get_abspath_ "$XDG_DATA_HOME" "$HOME/.local/share")
  XDG_STATE_HOME=$(_get_abspath_ "$XDG_STATE_HOME" "$HOME/.local/state")
  XDG_CACHE_HOME=$(_get_abspath_ "$XDG_CACHE_HOME" "$HOME/.cache")

  # The config has all over variables, so just this relative path is at the top;
  # it holds important values - all of the relative paths, as well as others
  # (CLODBOX_CREDENTIALS_PATH, CLODBOX_SETTINGS_PATH). Other standard paths use
  # the standard relative path loaded from the config file.

  if [ ! -f "$CLODBOX_CONFIG_FILE" ]; then
    $_ECHO_ "Error: [$CLODBOX_CONFIG_FILE] is missing. Reinstall to fix."
    exit 1
  else
    . $CLODBOX_CONFIG_FILE
  fi

  CLODBOX_DATA_PATH="$XDG_DATA_HOME/$CLODBOX_RELATIVE_STD_PATH" # projects, creds.
  CLODBOX_STATE_PATH="$XDG_STATE_HOME/$CLODBOX_REALTIVE_STD_PATH" # Maybe for later
  CLODBOX_CACHE_PATH="$XDG_CACHE_HOME/$CLODBOX_REALTIVE_STD_PATH" # Maybe for later
  CLODBOX_CREDENTIALS_PATH="$CLODBOX_DATA_PATH/$CLODBOX_INIT_CREDENTIALS_PATH"

  # Make sure all of the directories exist.
  $_MKDIR_ -p "$($_DIRNAME_ $CLODBOX_CONFIG_FILE)"
  $_MKDIR_ -p "$CLODBOX_DATA_PATH"
  $_MKDIR_ -p "$CLODBOX_STATE_PATH"
  $_MKDIR_ -p "$CLODBOX_CACHE_PATH"
}

# Fetch / construct and validate project paths.
_clodbox_fetch_project_paths_() {
  # Fetch / construct various project-related paths
  PROJECT_PATH="$($_REALPATH_ -m $($_PWD_))"
  PROJECT_HASH=$($_ECHO_ -n "$PROJECT_PATH" | $_SHA_ | $_CUT_ -d " " -f1)

  PROJECT_SETTINGS_PATH="$CLODBOX_DATA_PATH/$CLODBOX_PROJECTS_PATH/$PROJECT_HASH"
  PROJECT_DOT_PATH="$PROJECT_SETTINGS_PATH/$CLODBOX_DOT_PATH"
  PROJECT_CFG_FILE="$PROJECT_SETTINGS_PATH/$CLODBOX_CFG_FILE"

 # If the project path doesn't exist... something is wrong.
  if [ ! -d "$PROJECT_PATH" ]; then
    $_ECHO_ "Error: Project path '$PROJECT_PATH' does not exist." >&2
    $_ECHO_ "(How did you get here?!)" >&2
    exit 1
  fi

  # If there's no data on the project, attempt to initialize it freshly.
  if [ ! -d "$PROJECT_SETTINGS_PATH" ]; then
    $_PRINTF_ "[One Time Setup] Initializing clodbox in $PROJECT_PATH... "
    _clodbox_init_
    $_PRINTF_ "done.\n"
  fi

  # If dot-path doesn't exist at this point, its a problem; attempt recovery.
  if [ ! -d "$PROJECT_DOT_PATH" ]; then
    $_ECHO_ "Warning: No settings directory; this is probably a problem." >&2
    $_ECHO_ "--> Making project settings directory for attempted start..."
    $_MKDIR_ -p "$PROJECT_DOT_PATH"
      if [ ! -d "$PROJECT_DOT_PATH" ]; then
        $_ECHO_ "Error: *Still* no project settings directory. Exiting." >&2
        exit 1
      fi
  fi

  # If the config file doesn't exist, that's also a problem - attempt recovery.
  if [ ! -f "$PROJECT_CFG_FILE" ]; then
    $_ECHO_ "Warning: No project config file; this is probably a problem." >&2
    $_ECHO_ "--> Creating $PROJECT_CFG_FILE..."
    $_TOUCH_ "$PROJECT_CFG_FILE" >&2

      if [ ! -f "$PROJECT_CFG_FILE" ]; then
        $_ECHO_ "Error: *Still* no project config file. Exiting." >&2
        exit 1
      fi
  fi
}

# Initialize clodbox in current working path.
_clodbox_init_() {
  # Check if path exists. (It should always exist.)
  if [ ! -d "$PROJECT_PATH" ]; then
    $_ECHO_ "Function Error: clodbox project directory doesn't exist." 2>&1
    $_ECHO_ "(How did you get here?!)" >&2
    exit 1
  fi

  # Fetch project-specific path via hash. Generate missing directories.
  $_MKDIR_ -p "$PROJECT_PATH"
  $_MKDIR_ -p "$PROJECT_SETTINGS_PATH"

  # Copy credential files into the project configuration and exit.
  $_CP_ -rp "$CLODBOX_CREDENTIALS_PATH/." "$PROJECT_SETTINGS_PATH"
}

# Kickoff the script.
_clodbox_start_
